sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod
  - ng test --watch false

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
